#@TYPE: Machine
#@NAME: Raspberry Pi 4 Telemetry
#@DESCRIPTION: Raspberry Pi 4 machine config for telemetry project

require conf/machine/raspberrypi4-64.conf

KERNEL_MODULE_AUTOLOAD += "mcp251x spi-bcm2835 i2c-bcm2835 i2c-dev"

RPI_EXTRA_CONFIG = '\ndtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25\ndtparam=spi=on\ndtparam=i2c_arm=on\n'

MACHINE_FEATURES += "can"
