# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pi4-telemetry"
BBFILE_PATTERN_meta-pi4-telemetry = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pi4-telemetry = "6"

LAYERDEPENDS_meta-pi4-telemetry = "core"
LAYERSERIES_COMPAT_meta-pi4-telemetry = "scarthgap"
